version: '3'

services:
  kubekit:
    image: ${IMG_NAME}
    container_name: ${HOSTNAME}
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN}
    volumes:
      - ./data/shared:/root/shared
    # restart: always
    ports:
      - ${PORT}
    env_file:
      - ./env/common.env
    environment:
      - __APPNAME___PORT=${PORT}
